/**
 * Mock Data for Place Search Component
 * 
 * This file contains sample data for demonstrating the UI.
 * Will be replaced with actual API calls when backend is connected.
 */

// Sample countries from the database
export const MOCK_COUNTRIES = [
  { id: 1, name: 'Japan', type: 'country' },
  { id: 2, name: 'India', type: 'country' },
  { id: 3, name: 'Italy', type: 'country' },
  { id: 4, name: 'France', type: 'country' },
  { id: 5, name: 'Spain', type: 'country' },
  { id: 6, name: 'Thailand', type: 'country' },
  { id: 7, name: 'United States', type: 'country' },
  { id: 8, name: 'Australia', type: 'country' },
];

// Sample states
export const MOCK_STATES = [
  { id: 1, name: 'Tokyo', type: 'state', parent: 'Japan', country_id: 1 },
  { id: 2, name: 'Kyoto', type: 'state', parent: 'Japan', country_id: 1 },
  { id: 3, name: 'Maharashtra', type: 'state', parent: 'India', country_id: 2 },
  { id: 4, name: 'Rajasthan', type: 'state', parent: 'India', country_id: 2 },
  { id: 5, name: 'Tuscany', type: 'state', parent: 'Italy', country_id: 3 },
  { id: 6, name: 'California', type: 'state', parent: 'United States', country_id: 7 },
];

// Sample cities
export const MOCK_CITIES = [
  { id: 1, name: 'Tokyo', type: 'city', parent: 'Tokyo, Japan', state_id: 1 },
  { id: 2, name: 'Kyoto', type: 'city', parent: 'Kyoto, Japan', state_id: 2 },
  { id: 3, name: 'Mumbai', type: 'city', parent: 'Maharashtra, India', state_id: 3 },
  { id: 4, name: 'Jaipur', type: 'city', parent: 'Rajasthan, India', state_id: 4 },
  { id: 5, name: 'Florence', type: 'city', parent: 'Tuscany, Italy', state_id: 5 },
  { id: 6, name: 'San Francisco', type: 'city', parent: 'California, United States', state_id: 6 },
];

// Combined suggestions for autocomplete
export const MOCK_SUGGESTIONS = [
  // Countries
  { id: 'c1', name: 'Japan', type: 'country', parent: null },
  { id: 'c2', name: 'India', type: 'country', parent: null },
  { id: 'c3', name: 'Italy', type: 'country', parent: null },
  { id: 'c4', name: 'France', type: 'country', parent: null },
  { id: 'c5', name: 'Spain', type: 'country', parent: null },
  { id: 'c6', name: 'Thailand', type: 'country', parent: null },
  { id: 'c7', name: 'United States', type: 'country', parent: null },
  { id: 'c8', name: 'Australia', type: 'country', parent: null },
  
  // States
  { id: 's1', name: 'Tokyo', type: 'state', parent: 'Japan' },
  { id: 's2', name: 'Kyoto', type: 'state', parent: 'Japan' },
  { id: 's3', name: 'Maharashtra', type: 'state', parent: 'India' },
  { id: 's4', name: 'Rajasthan', type: 'state', parent: 'India' },
  { id: 's5', name: 'Tuscany', type: 'state', parent: 'Italy' },
  { id: 's6', name: 'California', type: 'state', parent: 'United States' },
  
  // Cities
  { id: 'city1', name: 'Tokyo', type: 'city', parent: 'Tokyo, Japan' },
  { id: 'city2', name: 'Kyoto', type: 'city', parent: 'Kyoto, Japan' },
  { id: 'city3', name: 'Mumbai', type: 'city', parent: 'Maharashtra, India' },
  { id: 'city4', name: 'Jaipur', type: 'city', parent: 'Rajasthan, India' },
  { id: 'city5', name: 'Florence', type: 'city', parent: 'Tuscany, Italy' },
  { id: 'city6', name: 'San Francisco', type: 'city', parent: 'California, USA' },
  { id: 'city7', name: 'Paris', type: 'city', parent: 'Île-de-France, France' },
  { id: 'city8', name: 'Barcelona', type: 'city', parent: 'Catalonia, Spain' },
  
  // Places
  { id: 'p1', name: 'Senso-ji Temple', type: 'place', parent: 'Tokyo, Japan' },
  { id: 'p2', name: 'Fushimi Inari Shrine', type: 'place', parent: 'Kyoto, Japan' },
  { id: 'p3', name: 'Gateway of India', type: 'place', parent: 'Mumbai, India' },
  { id: 'p4', name: 'Hawa Mahal', type: 'place', parent: 'Jaipur, India' },
  { id: 'p5', name: 'Uffizi Gallery', type: 'place', parent: 'Florence, Italy' },
  { id: 'p6', name: 'Golden Gate Bridge', type: 'place', parent: 'San Francisco, USA' },
];

// Sample places with full data structure matching the database schema
export const MOCK_PLACES = [
  {
    id: 1,
    name: 'Senso-ji Temple',
    city_name: 'Tokyo',
    state_name: 'Tokyo',
    country_name: 'Japan',
    ai_summary: 'Senso-ji is Tokyo\'s oldest and most significant Buddhist temple, located in Asakusa. The temple\'s iconic red lantern and Thunder Gate (Kaminarimon) make it one of Japan\'s most photographed landmarks.',
    suggested_duration: '2-3 hours',
    best_time_to_visit: 'Early morning',
    place_tip: 'Visit early in the morning to avoid crowds and experience the peaceful atmosphere. The Nakamise shopping street opens around 10 AM.',
    cost: 'free',
    rating_tourist_priority: 5,
    rating_traveler_experience: 5,
    latitude: 35.7148,
    longitude: 139.7967,
    address: '2-3-1 Asakusa, Taito City, Tokyo 111-0032, Japan',
    official_website: 'https://www.senso-ji.jp/',
    rank_score: 9.8,
    sunrise_view: true,
    sunset_view: false,
    advanced_booking: 'not_required',
    photo_url: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=600',
    tags: ['temple', 'historic', 'cultural', 'photography'],
    opening_hours: {
      monday: '6:00 AM - 5:00 PM',
      tuesday: '6:00 AM - 5:00 PM',
      wednesday: '6:00 AM - 5:00 PM',
      thursday: '6:00 AM - 5:00 PM',
      friday: '6:00 AM - 5:00 PM',
      saturday: '6:00 AM - 5:00 PM',
      sunday: '6:00 AM - 5:00 PM',
    },
  },
  {
    id: 2,
    name: 'Fushimi Inari Shrine',
    city_name: 'Kyoto',
    state_name: 'Kyoto',
    country_name: 'Japan',
    ai_summary: 'Famous for its thousands of vermillion torii gates, Fushimi Inari-taisha is the head shrine of Inari, located at the base of Mount Inari. The trails behind the shrine lead through a stunning tunnel of gates.',
    suggested_duration: '3-4 hours',
    best_time_to_visit: 'Sunrise or late afternoon',
    place_tip: 'Hike to the summit for panoramic views of Kyoto. The shrine is open 24/7, so consider visiting at dawn for the best photos.',
    cost: 'free',
    rating_tourist_priority: 5,
    rating_traveler_experience: 5,
    latitude: 34.9671,
    longitude: 135.7727,
    address: '68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto, 612-0882, Japan',
    official_website: 'https://fushimiinari.jp/',
    rank_score: 9.9,
    sunrise_view: true,
    sunset_view: true,
    advanced_booking: 'not_required',
    photo_url: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600',
    tags: ['shrine', 'hiking', 'photography', 'spiritual'],
  },
  {
    id: 3,
    name: 'Gateway of India',
    city_name: 'Mumbai',
    state_name: 'Maharashtra',
    country_name: 'India',
    ai_summary: 'The Gateway of India is an iconic arch monument built during the British Raj to commemorate the landing of King George V and Queen Mary in 1911. Located at the waterfront in Mumbai, it offers stunning views of the Arabian Sea.',
    suggested_duration: '1-2 hours',
    best_time_to_visit: 'Evening for sunset',
    place_tip: 'Best visited during sunset for beautiful photos. Take a boat ride to Elephanta Caves from here.',
    cost: 'free',
    rating_tourist_priority: 4,
    rating_traveler_experience: 4,
    latitude: 18.9220,
    longitude: 72.8347,
    address: 'Apollo Bandar, Colaba, Mumbai, Maharashtra 400001, India',
    official_website: null,
    rank_score: 8.5,
    sunrise_view: true,
    sunset_view: true,
    advanced_booking: 'not_required',
    photo_url: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=600',
    tags: ['monument', 'historic', 'landmark', 'waterfront'],
  },
  {
    id: 4,
    name: 'Hawa Mahal',
    city_name: 'Jaipur',
    state_name: 'Rajasthan',
    country_name: 'India',
    ai_summary: 'The Palace of Winds is a stunning five-story pink sandstone structure with 953 small windows (jharokhas). Built in 1799, it was designed to allow royal women to observe street life without being seen.',
    suggested_duration: '1-2 hours',
    best_time_to_visit: 'Morning for best photography',
    place_tip: 'Visit early morning when the sun illuminates the facade beautifully. The best photos are taken from across the street.',
    cost: 'low',
    rating_tourist_priority: 5,
    rating_traveler_experience: 4,
    latitude: 26.9239,
    longitude: 75.8267,
    address: 'Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Pink City, Jaipur, Rajasthan 302002, India',
    official_website: null,
    rank_score: 9.2,
    sunrise_view: true,
    sunset_view: false,
    advanced_booking: 'not_required',
    photo_url: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600',
    tags: ['palace', 'architecture', 'historic', 'photography'],
  },
  {
    id: 5,
    name: 'Uffizi Gallery',
    city_name: 'Florence',
    state_name: 'Tuscany',
    country_name: 'Italy',
    ai_summary: 'The Uffizi Gallery is one of the world\'s most important art museums, housing masterpieces from the Italian Renaissance including works by Botticelli, Michelangelo, Leonardo da Vinci, and Raphael.',
    suggested_duration: '3-4 hours',
    best_time_to_visit: 'Weekday mornings',
    place_tip: 'Book tickets online in advance to skip the long queues. Audio guides are highly recommended for a richer experience.',
    cost: 'high',
    rating_tourist_priority: 5,
    rating_traveler_experience: 5,
    latitude: 43.7687,
    longitude: 11.2559,
    address: 'Piazzale degli Uffizi, 6, 50122 Firenze FI, Italy',
    official_website: 'https://www.uffizi.it/',
    rank_score: 9.7,
    sunrise_view: false,
    sunset_view: false,
    advanced_booking: 'recommended',
    photo_url: 'https://images.unsplash.com/photo-1541370976299-4d24ebbc9077?w=600',
    tags: ['museum', 'art', 'renaissance', 'cultural'],
    opening_hours: {
      monday: 'Closed',
      tuesday: '8:15 AM - 6:50 PM',
      wednesday: '8:15 AM - 6:50 PM',
      thursday: '8:15 AM - 6:50 PM',
      friday: '8:15 AM - 6:50 PM',
      saturday: '8:15 AM - 6:50 PM',
      sunday: '8:15 AM - 6:50 PM',
    },
  },
  {
    id: 6,
    name: 'Golden Gate Bridge',
    city_name: 'San Francisco',
    state_name: 'California',
    country_name: 'United States',
    ai_summary: 'The Golden Gate Bridge is an iconic suspension bridge spanning the Golden Gate strait. Its distinctive International Orange color and Art Deco styling make it one of the most photographed bridges in the world.',
    suggested_duration: '2-3 hours',
    best_time_to_visit: 'Clear mornings',
    place_tip: 'For the best views, visit the Battery Spencer viewpoint on the north side. Rent bikes to cycle across the bridge.',
    cost: 'free',
    rating_tourist_priority: 5,
    rating_traveler_experience: 5,
    latitude: 37.8199,
    longitude: -122.4783,
    address: 'Golden Gate Bridge, San Francisco, CA, USA',
    official_website: 'https://www.goldengate.org/',
    rank_score: 9.6,
    sunrise_view: true,
    sunset_view: true,
    advanced_booking: 'not_required',
    photo_url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600',
    tags: ['bridge', 'landmark', 'photography', 'iconic'],
  },
  {
    id: 7,
    name: 'Eiffel Tower',
    city_name: 'Paris',
    state_name: 'Île-de-France',
    country_name: 'France',
    ai_summary: 'The Eiffel Tower is the most iconic symbol of Paris and one of the most recognizable structures in the world. Standing at 330 meters, it offers breathtaking panoramic views of the entire city.',
    suggested_duration: '2-3 hours',
    best_time_to_visit: 'Evening for the light show',
    place_tip: 'Visit at night to see the tower sparkle every hour. Book tickets online to avoid 2-3 hour queues.',
    cost: 'medium',
    rating_tourist_priority: 5,
    rating_traveler_experience: 5,
    latitude: 48.8584,
    longitude: 2.2945,
    address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France',
    official_website: 'https://www.toureiffel.paris/',
    rank_score: 9.9,
    sunrise_view: true,
    sunset_view: true,
    advanced_booking: 'recommended',
    photo_url: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=600',
    tags: ['landmark', 'tower', 'romantic', 'viewpoint'],
    opening_hours: {
      monday: '9:30 AM - 11:45 PM',
      tuesday: '9:30 AM - 11:45 PM',
      wednesday: '9:30 AM - 11:45 PM',
      thursday: '9:30 AM - 11:45 PM',
      friday: '9:30 AM - 11:45 PM',
      saturday: '9:30 AM - 11:45 PM',
      sunday: '9:30 AM - 11:45 PM',
    },
  },
  {
    id: 8,
    name: 'La Sagrada Familia',
    city_name: 'Barcelona',
    state_name: 'Catalonia',
    country_name: 'Spain',
    ai_summary: 'Antoni Gaudí\'s masterpiece, the Sagrada Familia, is an extraordinary basilica that has been under construction since 1882. Its unique Gothic and Art Nouveau architecture makes it a UNESCO World Heritage Site.',
    suggested_duration: '2-3 hours',
    best_time_to_visit: 'Morning for best interior lighting',
    place_tip: 'Book tickets with tower access for stunning city views. Visit in the afternoon to see the colorful light through stained glass windows.',
    cost: 'medium',
    rating_tourist_priority: 5,
    rating_traveler_experience: 5,
    latitude: 41.4036,
    longitude: 2.1744,
    address: 'C/ de Mallorca, 401, 08013 Barcelona, Spain',
    official_website: 'https://sagradafamilia.org/',
    rank_score: 9.8,
    sunrise_view: false,
    sunset_view: false,
    advanced_booking: 'recommended',
    photo_url: 'https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?w=600',
    tags: ['basilica', 'architecture', 'gaudi', 'unesco'],
    opening_hours: {
      monday: '9:00 AM - 8:00 PM',
      tuesday: '9:00 AM - 8:00 PM',
      wednesday: '9:00 AM - 8:00 PM',
      thursday: '9:00 AM - 8:00 PM',
      friday: '9:00 AM - 8:00 PM',
      saturday: '9:00 AM - 8:00 PM',
      sunday: '9:00 AM - 8:00 PM',
    },
  },
];

export default {
  MOCK_COUNTRIES,
  MOCK_STATES,
  MOCK_CITIES,
  MOCK_SUGGESTIONS,
  MOCK_PLACES,
};
