# Purpose: Adds valid file-purpose headers and regenerates this complete source/configuration file guide.
"""Add legal file-purpose comments and generate the complete published-file guide.

Strict JSON, generated schemas/lockfiles and binary assets are explained in the
guide instead of inserting invalid comments. Existing code semantics are preserved.
"""
import ast
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GUIDE = ROOT / 'docs/files.md'
SPECIAL = {
    'start.py': 'Sets up isolated dependencies once, starts API/web/admin, checks readiness, and stops only its owned services.',
    'services/api/requirements.txt': 'Pins the Flask API runtime dependencies, database drivers, authentication, workers and export integrations.',
    'services/api/requirements-dev.txt': 'Pins the test, critical-error lint and infrastructure validation tools excluded from the production image.',
    'README.md': 'Project overview and the shortest setup/start/verification instructions.',
    '.gitignore': 'Excludes local settings, secrets, data, dependencies, build output, and archived extras from publication.',
    '.gitattributes': 'Keeps shell/workflow line endings portable and treats SQLite catalogs as binary data.',
    'package.json': 'Defines workspace commands, pinned package-manager version, and shared development dependencies.',
    'pnpm-workspace.yaml': 'Declares application, API, and shared-package workspace membership and permitted dependency build scripts.',
    'pnpm-lock.yaml': 'Locks resolved workspace dependencies for reproducible installation; generated by pnpm.',
    'turbo.json': 'Orders and caches workspace build/lint/type-check tasks while keeping tests fresh and development processes persistent.',
    'prettier.config.cjs': 'Loads the shared formatting preset for repository configuration and new source files.',
    'data/catalog/travel_data_complete.db': 'Reference place/location catalog used for travel search; preserve the binary dataset without source comments.',
    'infra/docker/docker-compose.yml': 'Runs local PostgreSQL, Redis, API, and optional worker with persistent database/catalog/upload volumes.',
    'infra/github/workflows/ci.yml': 'Canonical CI: install locked dependencies, check source, run tests/builds, and verify generated API declarations.',
    'infra/github/workflows/deploy.yml': 'Canonical release workflow: verify source, then call the configured staging or production deployment hook.',
    'infra/tools/check_structure.py': 'Checks required workspace files, discovered workflows, and Python/JavaScript/TypeScript import targets.',
    'infra/tools/check_python.py': 'Validates backend Python files against the Python 3.11 grammar used by CI and Docker.',
    'infra/tools/validate_infra.py': 'Checks Compose paths, volumes and dependencies plus workflow YAML without claiming live deployment.',
    'infra/tools/sync-workflows.mjs': 'Copies canonical workflows into the .github/workflows paths GitHub discovers.',
    'infra/tools/export_openapi.py': 'Exports registered Flask paths and explicit admin schemas using a migrated disposable database.',
    'infra/tools/document_files.py': 'Adds valid file-purpose headers and regenerates this complete source/configuration file guide.',
    'infra/tools/dev-env.ps1': 'Creates the optional isolated development environment without replacing archived local environments.',
    'docs/files.md': 'Explains every published file, including strict JSON, generated artifacts and binary assets that cannot contain comments.',
    'docs/architecture.md': 'Explains app/service/package boundaries, data ownership, auth and deployment architecture.',
    'docs/api.md': 'Explains API envelopes, cookie authentication, generated client use and remaining schema coverage.',
    'docs/runbook.md': 'Documents operation, verification, backups, and deployment prerequisites.',
    'docs/startup.md': 'Documents the single-file launcher, one-time setup, runtime modes, ports, data and troubleshooting.',
    'packages/api-client/src/index.ts': 'Creates the generated-schema API client with cookie credentials and mutation CSRF headers, without automatic retries.',
    'packages/types/src/index.ts': 'Exports shared UUID, money, account, API envelope and service-health TypeScript contracts.',
}
DETAIL = {
    'AuthContext': 'Provides authenticated account state, initialization, profile updates, and logout cache cleanup.',
    'useExpenseQuery': 'Coordinates React Query reads and mutations for expense groups, balances, expenses and settlements.',
    'useChatQuery': 'Manages paginated chat queries and optimistic sends while preserving concurrent messages.',
    'useChatSocket': 'Connects cookie-authenticated live chat and reports socket authentication/connection failures.',
    'useGroupSocket': 'Subscribes to cookie-authenticated trip workspace activity updates.',
    'ChatPanel': 'Coordinates message rendering, live chat, AI cards, polls, optimistic sends and group-switch state.',
    'PollFeed': 'Renders poll choices, vote counts and voter panels using state and handlers supplied by chat.',
    'ScoutConsentCard': 'Displays Scout consent choices and retries the original request after consent.',
    'CrewCards': 'Renders Crew question, confirmation, place and success cards.',
    'aiBots': 'Defines the shared Scout and Crew bot identities used by chat and member views.',
    'Toast': 'Renders shared timed notifications used by application features.',
    'ExpenseManager': 'Coordinates personal/group expense screens, editing, history and financial query updates.',
    'GroupManager': 'Displays and manages expense groups, members, ownership controls and invitations.',
    'SettlementModal': 'Collects debt-bounded settlement payments and displays currency-aware history and save errors.',
    'apiClient': 'Sends web API requests with cookie credentials, CSRF headers, response handling and cancellation.',
    'sqlAuthService': 'Handles cookie-based signup/login/refresh/profile/logout requests and session failure behavior.',
    'chatCache': 'Deduplicates message IDs across cached pages and reconciles optimistic send results.',
    'money': 'Normalizes currency amounts, whole-cent splits and UUID payer changes.',
    'queryClientPersist': 'Configures query caching while excluding financial/private queries and mutation state from persistence.',
    'indexedDBPersister': 'Stores and removes permitted query snapshots in IndexedDB.',
    'InactivityTracker': 'Warns about inactivity and resets the logout timer when activity resumes.',
    'FeatureErrorBoundary': 'Contains feature rendering failures and provides an actionable recovery screen.',
    'TripMap': 'Renders itinerary map markers and safe DOM-based popups.',
    'SearchBar': 'Fetches autocomplete suggestions and ignores cancelled or stale responses.',
    'PlaceSearchPage': 'Coordinates real place search, statistics and loading/error/empty states.',
}


def files():
    output = subprocess.check_output(['git', 'ls-files', '--cached', '--others', '--exclude-standard', '-z'], cwd=ROOT)
    names = {item.decode() for item in output.split(b'\0') if item}
    names.add('docs/files.md')
    return sorted(name for name in names if not name.startswith(('extra/', '.tripraft/')) and ((ROOT / name).is_file() or name == 'docs/files.md'))


def words(value):
    return re.sub(r'(?<=[a-z0-9])(?=[A-Z])', ' ', value.replace('_', ' ').replace('-', ' '))


def purpose(name):
    if name in SPECIAL:
        return SPECIAL[name]
    path = Path(name)
    stem = path.stem
    if '/generated/' in name or name.endswith('openapi.json'):
        return 'Generated API route/response contracts; regenerate through the documented OpenAPI tools rather than editing by hand.'
    if name.startswith('.github/workflows/'):
        return 'GitHub discovery copy of infra/github/workflows/' + path.name + '; update the canonical file and run pnpm workflows:sync.'
    if path.name == '.env.example':
        return 'Documents public configuration keys and placeholder values; copy locally and keep real credentials out of Git.'
    if '/tests/' in name or '/__tests__/' in name:
        if path.name.startswith('test_') or '.test.' in path.name:
            return 'Regression tests for ' + words(stem.replace('.test', '').removeprefix('test_')) + ', including success and failure behavior.'
        return 'Test fixture/configuration helper for ' + words(stem) + '.'
    if stem in DETAIL:
        return DETAIL[stem]
    if path.suffix == '.py':
        try:
            doc = ast.get_docstring(ast.parse((ROOT / name).read_text(encoding='utf-8-sig')))
        except (SyntaxError, OSError):
            doc = None
        if doc:
            lines = [line.strip(' =-') for line in doc.splitlines() if line.strip(' =-')]
            if lines:
                return ' '.join(lines[:2])[:220].rstrip('.') + '.'
        if path.name == '__init__.py':
            return 'Declares the ' + str(path.parent).replace('/', '.') + ' Python package and its public exports.'
        return 'Implements ' + words(stem) + ' for the ' + str(path.parent) + ' backend module.'
    if path.name == 'package.json':
        return 'Declares dependencies, exports and development commands for the ' + str(path.parent) + ' workspace package.'
    if 'tsconfig' in path.name:
        return 'Selects TypeScript compiler options and checked source for ' + str(path.parent) + '.'
    if 'eslint' in path.name:
        return 'Applies the shared syntax/error lint rules to ' + str(path.parent) + '.'
    if 'vite.config' in path.name:
        return 'Configures the React build and local API proxy for ' + str(path.parent) + '.'
    if path.suffix == '.css':
        return 'Styles the ' + words(stem) + ' interface, including its layout and interaction states.'
    if path.suffix in {'.svg', '.png', '.jpg', '.ico'}:
        return 'Visual asset used by ' + str(path.parent) + ': ' + words(stem) + '.'
    if name.startswith('apps/admin/src/'):
        return 'Renders the admin console with initialized server-account authorization, readiness and ingestion audit results.'
    if path.name == 'main.tsx':
        return 'Mounts the React application into the HTML root element.'
    if path.suffix in {'.jsx', '.tsx'}:
        return 'Renders the ' + words(stem) + ' interface within ' + str(path.parent) + '.'
    if stem.startswith('use'):
        return 'Provides reusable React state/query behavior for ' + words(stem[3:]) + '.'
    if path.suffix in {'.js', '.ts', '.cjs', '.mjs'}:
        return 'Provides ' + words(stem) + ' logic and exports for ' + str(path.parent) + '.'
    if path.name == 'Dockerfile':
        return 'Builds the non-root Python API image and its production entry point.'
    if path.name == 'docker-entrypoint.sh':
        return 'Copies the seed catalog only when needed, applies API migrations and starts the supplied server/worker command.'
    if path.suffix == '.html':
        return 'Defines the HTML document/root element loaded by the React frontend.'
    if path.suffix == '.md':
        return 'Documents ' + words(stem) + ' for ' + str(path.parent) + '.'
    return 'Configures ' + words(stem.lstrip('.')) + ' for ' + str(path.parent) + '.'


def annotate(name, description):
    path = ROOT / name
    if not path.exists() or name.endswith('openapi.json') or '/generated/' in name or name == 'pnpm-lock.yaml':
        return False
    suffix = path.suffix
    prefix = '#' if suffix in {'.py', '.ps1', '.sh', '.yml', '.yaml', '.toml', '.ini'} or path.name in {'.env.example', '.gitignore', '.gitattributes', '.dockerignore', 'Dockerfile'} else '//'
    if suffix in {'.json', '.db', '.csv', '.md'}:
        return False  # These files are explained in the guide; their syntax is preserved.
    if suffix not in {'.py', '.ps1', '.sh', '.yml', '.yaml', '.toml', '.ini', '.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.css', '.html', '.svg'} and path.name not in {'.env.example', '.gitignore', '.gitattributes', '.dockerignore', 'Dockerfile'}:
        return False
    content = path.read_text(encoding='utf-8-sig')
    if 'Purpose:' in '\n'.join(content.splitlines()[:4]):
        if suffix in {'.sh', '.yml', '.yaml'} and b'\r\n' in path.read_bytes():
            path.write_text(content, encoding='utf-8', newline='\n')
            return True
        return False
    if '@jest-environment' in content[:300]:
        return False
    comment = f'{prefix} Purpose: {description}\n'
    if suffix == '.css':
        comment = f'/* Purpose: {description} */\n'
    if suffix in {'.html', '.svg'}:
        comment = f'<!-- Purpose: {description} -->\n'
    lines = content.splitlines(keepends=True)
    position = 1 if lines and (lines[0].startswith('#!') or lines[0].startswith('<?xml')) else 0
    candidate = ''.join(lines[:position]) + comment + ''.join(lines[position:])
    if suffix == '.py':
        assert ast.dump(ast.parse(content)) == ast.dump(ast.parse(candidate)), f'Annotation changed Python behavior: {name}'
    path.write_text(candidate, encoding='utf-8', newline='\n')
    return True


if __name__ == '__main__':
    names = files()
    changed = sum(annotate(name, purpose(name)) for name in names if not name.startswith('.github/workflows/'))
    rows = ['# Published file guide', '', 'Every published source/configuration file is listed below. Legal source formats have purpose comments; strict JSON, generated contracts/lockfiles and binary assets are described here without invalid edits.', '', '| File | What it does |', '|---|---|']
    for name in names:
        rows.append(f'| `{name}` | {purpose(name).replace("|", "/")} |')
    GUIDE.write_text('\n'.join(rows) + '\n', encoding='utf-8')
    print(f'Documented {len(names)} published files; added {changed} legal purpose comments with unchanged Python ASTs.')
