# Purpose: Retire the unsafe integer-to-UUID schema rewrite. Revision ID: 74866d910457.
"""Retire the unsafe integer-to-UUID schema rewrite.

Revision ID: 74866d910457
Revises: c4d5e6f7a8b9

The original autogenerated migration attempted hundreds of type changes with
no PostgreSQL ``USING`` expression and without rebuilding dependent foreign
keys. It could therefore corrupt or leave a partially rewritten production
database. Fresh installations get UUID columns from the repaired baseline.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import context, op
from app.core.db.migration_checks import assert_uuid_storage


revision: str = '74866d910457'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _legacy_integer_primary_key_tables(connection) -> list[str]:
    """Return application tables whose primary-key ``id`` is still integer."""
    inspector = sa.inspect(connection)
    legacy_tables: list[str] = []
    for table_name in inspector.get_table_names():
        primary_key = (
            inspector.get_pk_constraint(table_name).get('constrained_columns') or []
        )
        if primary_key != ['id']:
            continue
        columns = {
            column['name']: column['type']
            for column in inspector.get_columns(table_name)
        }
        if isinstance(columns.get('id'), (sa.Integer, sa.SmallInteger, sa.BigInteger)):
            legacy_tables.append(table_name)
    return legacy_tables


def upgrade() -> None:
    """Allow UUID-native schemas; reject unsafe legacy rewrites explicitly."""
    if context.is_offline_mode():
        # The frozen baseline already supplies UUIDs in fresh-install SQL.
        return
    assert_uuid_storage(op.get_bind())
    legacy_tables = _legacy_integer_primary_key_tables(op.get_bind())
    if legacy_tables:
        table_list = ', '.join(sorted(legacy_tables))
        raise RuntimeError(
            'Legacy integer primary keys remain in: '
            f'{table_list}. Refusing the retired automatic UUID rewrite. '
            'Use a reviewed, backup-tested data migration that converts '
            'primary keys and dependent foreign keys together.'
        )


def downgrade() -> None:
    """The old destructive rewrite cannot be safely reversed automatically."""
