// Purpose: Regression tests for cache And Freshness, including success and failure behavior.
import React from 'react';import {renderHook,waitFor} from '@testing-library/react';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
jest.mock('../services/expenseApi',()=>({__esModule:true,default:{getMegaBootstrap:jest.fn()}}));jest.mock('../lib/indexedDBPersister',()=>({createIDBPersister:jest.fn()}));jest.mock('@tanstack/react-query-persist-client',()=>({persistQueryClient:jest.fn()}));
import expense from '../services/expenseApi';import {useMegaBootstrap,queryKeys} from '../hooks/useExpenseQuery';import {createQueryClient,shouldPersistQuery,initializeQueryPersistence,clearPersistedCache} from '../lib/queryClientPersist';import {persistQueryClient} from '@tanstack/react-query-persist-client';import {createIDBPersister} from '../lib/indexedDBPersister';
it.each([['expenses','g'],['expense-history','id'],['settlements','g'],['balances','g'],['user'],['chat','messages','g'],['aiConsent','g'],['group','g'],['mega-bootstrap','g'],['recent-history','g'],['invitations']])('does not persist private query %s',(...key)=>expect(shouldPersistQuery(key)).toBe(false));
it('does not automatically retry mutations',()=>{const client=createQueryClient();expect(client.getDefaultOptions().mutations.retry).toBe(0);expect(client.getQueryDefaults(['expenses']).staleTime).toBe(0);client.clear();});
it('invalidates older localStorage snapshots and never dehydrates mutations',async()=>{const client=new QueryClient();await initializeQueryPersistence(client);expect(persistQueryClient).toHaveBeenCalledWith(expect.objectContaining({buster:'frontend-audit-2026-10-03'}));expect(persistQueryClient.mock.calls[0][0].dehydrateOptions.shouldDehydrateMutation({})).toBe(false);client.clear();});
it('clears both persistence stores at logout through the actual persister',async()=>{localStorage.setItem('TRIPRAFT_QUERY_CACHE','old');global.indexedDB={};const removeClient=jest.fn();createIDBPersister.mockReturnValue({removeClient});await clearPersistedCache();expect(localStorage.getItem('TRIPRAFT_QUERY_CACHE')).toBeNull();expect(removeClient).toHaveBeenCalled();delete global.indexedDB;});
it('refetches bootstrap balances even when its old cache contains data',async()=>{const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(queryKeys.megaBootstrap('group'),{data:{active_group:{balances:[{user_id:'uuid',net_balance:100}]}}});expense.getMegaBootstrap.mockResolvedValue({data:{active_group:{group:{group_id:'group'},members:[],expenses:[],balances:[{user_id:'uuid',net_balance:5}]}}});const wrapper=({children})=><QueryClientProvider client={client}>{children}</QueryClientProvider>;const {result,unmount}=renderHook(()=>useMegaBootstrap('group'),{wrapper});await waitFor(()=>expect(result.current.data?.data.active_group.balances[0].net_balance).toBe(5));expect(expense.getMegaBootstrap).toHaveBeenCalledTimes(1);unmount();client.clear();});
