"""uuidv7_primary_keys

Revision ID: 74866d910457
Revises: c4d5e6f7a8b9
Create Date: 2026-03-26 15:27:18.199379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74866d910457'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('expense_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('expense_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('changed_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_expense_history_expense'))
        batch_op.drop_index(batch_op.f('idx_expense_history_user'))

    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('expense_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('paid_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('deleted_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_expenses_paid_by_date'))

    with op.batch_alter_table('gp_chat_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('parent_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('gp_chat_summaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('from_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('to_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('gp_checklist_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('completed_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('gp_group_activities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('gp_group_members', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('removed_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('gp_invitations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('invitee_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('invited_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('gp_itinerary_documents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('last_edited_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('gp_message_reads', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('last_read_message_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('gp_notifications', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('gp_place_votes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('place_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('gp_places', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('added_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_gp_places_geo'))

    with op.batch_alter_table('gp_poll_votes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('poll_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('gp_polls', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('gp_vault_documents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('group_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('removed_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('invitee_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('invited_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('from_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('to_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('recorded_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_settlements_group_date'))

    with op.batch_alter_table('travel_groups', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('expense_group_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_sessions_expires'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sessions_expires'), ['expires_at'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('travel_groups', schema=None) as batch_op:
        batch_op.alter_column('expense_group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_settlements_group_date'), ['group_id', 'settlement_date'], unique=False)
        batch_op.alter_column('recorded_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('to_user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('from_user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.alter_column('invited_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('invitee_user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('removed_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('group_balances', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_vault_documents', schema=None) as batch_op:
        batch_op.alter_column('uploaded_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_polls', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_poll_votes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('poll_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_gp_places_geo'), ['latitude', 'longitude'], unique=False)
        batch_op.alter_column('added_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_place_votes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('place_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_notifications', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_message_reads', schema=None) as batch_op:
        batch_op.alter_column('last_read_message_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_itinerary_documents', schema=None) as batch_op:
        batch_op.alter_column('last_edited_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_invitations', schema=None) as batch_op:
        batch_op.alter_column('invited_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('invitee_user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_group_members', schema=None) as batch_op:
        batch_op.alter_column('removed_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_group_activities', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_checklist_items', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('completed_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_chat_summaries', schema=None) as batch_op:
        batch_op.alter_column('to_message_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('from_message_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gp_chat_messages', schema=None) as batch_op:
        batch_op.alter_column('parent_message_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_expenses_paid_by_date'), ['paid_by', 'created_at'], unique=False)
        batch_op.alter_column('deleted_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('paid_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('expense_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('expense_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_expense_history_user'), ['changed_by', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_expense_history_expense'), ['expense_id', 'created_at'], unique=False)
        batch_op.alter_column('changed_by',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('expense_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
